### ISSUE TITLE
Issues with DirectXTex

### ISSUE THREAD

**Issue by Laythros** [fortross/SWGModelExporter#1]
Hello Fortross,

This looks very interesting and I was wondering if you can help with an Error I am getting.

I am getting the following:
1>LINK : fatal error LNK1104: cannot open file 'DirectXTex.lib'

I am pretty sure I don't have the directXTex project properly incorporated into your sln. As I have necer used the directXTex libs I am not sure how to proceed

**Comment by bhtrail** [comment]
https://github.com/Microsoft/DirectXTex just get it there and build from scratch

**Comment by Laythros** [comment]
Sweet thanks, sorry I missed that one.

Finally got it all complied can I get an example of how to use the command line to extract a mgn and skeleton?

**Comment by bhtrail** [comment]
`--swg-path=<path to your SWG location> --object=<name of object you want to extract> --output-path=<path to output folder>`

Better to use full object name (without extension, just name), because partial name could give weird result. Animation will not be extracted. Static meshes do not supported, only MGNs. MGN will be exported into binary FBX with associated skeletons (multiple skeletons will be joined to one), skinning and morph data. Textures will be converted to TGA format and exported also

Feel free to fork it and add features if you like
